export let CONST = {
  GAME_WIDTH: 1000,
  GAME_HEIGHT: 900,
  BASE_GAME_SPEED: 20,
  TITLE_SCENE: "TitleScene",
  MAIN_SCENE: "MainScene"
}

// Game grid constants.
export let GRID_CONST = {
  W_CELLS: 10,
  H_CELLS: 10,
  CELL_WIDTH: 64,
  CELL_HEIGHT: 64,
  BORDER_SIZE: 10,
}

// Conveyor constants.
export let CONVEYOR_CONST = {
  SHAPE_CAPACITY: 6,
  SHAPE_GEN_PERIOD: 170,
  SHAPE_GEN_ACTION_DELAY: 30,
  SHAPE_COUNT: 1,
  SHAPE_CELL_WIDTH: 30,
  SHAPE_CELL_HEIGHT: 30,
  SHAPE_CELL_BORDER_SIZE: 1,
  MEMORY_SHAPE_ROWS: 3,
  MEMORY_SHAPE_COLUMNS: 3,
  SPACING: 20,
  TILE_SIZE: 1000,
  CREATOR_SHAPE_COLOR: 0x00FF00,
  ERASER_SHAPE_COLOR: 0xFF0000,
  // TODO: Move this to a separate map.
  DEATH_TIMER_SECONDS: 4,
  DEATH_TIMER_FONT_SIZE: "32px",
}

// Robot constants.
export let ROBOT_CONST = {
  SPEED: 50,
}

export let TASK_CONST = {
  EXECUTION_TICKS: 60 * 4,
}

export let COLOR_CONST = {
  OCCUPIED_HOVER: 0xff0000,
  UNOCCUPIED_HOVER: 0x00ff00,
  CHOSEN_SHAPE_EMPHASIS: 0xffff00
}

export let SCORE_CONST = {
  B_BOX_W_START: CONST.GAME_WIDTH - CONST.GAME_WIDTH / 3,
  B_BOX_H_START: 16,
  TEXT_COLOR: "#FFFFFF",
  FONT_SIZE: '32px',
  TEXT_FILL: '#000',
  TITLE: "Score: ",
  GRID_CELL_VALUE: 1,
  GAME_SPEED_PER_SCORE_CHANGE: 1.0 / 200,
}

export let PLAYER_CONST = {
  STARTING_HEALTH: 5,
  STARTING_RECYCLES: 0,
  MAX_RECYCLES: 2,
}

export let RECYCLE_CONST = {
  B_BOX_W_START: CONST.GAME_WIDTH - CONST.GAME_WIDTH / 6,
  B_BOX_H_START: 16,
  TITLE: "Recycles: ",
  BONUS_ONE_FOR_SCORE: 50,
}
